apiVersion: batch/v1
kind: Job
metadata:
  name: native-job-seq-work
spec:
  parallelism: 4
  completions: 4
  template:
    metadata:
      labels:
        app: native-seq-work
    spec:
      nodeName: sdn2
      containers:
      - name: benchmark
        image: memory-benchmark:v_numa4
        command: ["/bin/bash", "-c"]
        args:
          - |
            export OUTPUT_DIR=/app/results/native_seq_${HOSTNAME}_work
            mkdir -p $OUTPUT_DIR
            export PATTERN='sequential'
            export EXPERIMENT_MODE='work'
            
            python3 /app/scripts/script_controlled.py --output-dir "$OUTPUT_DIR"
        securityContext: 
          privileged: true
        resources: 
          requests: { cpu: "2", memory: "7Gi" }
          limits: { cpu: "2", memory: "7Gi" }
        volumeMounts: 
          - name: results-volume
            mountPath: /app/results
          - name: script-python-volume
            mountPath: /app/scripts/script_controlled.py
            subPath: script_controlled.py
          - name: script-python-volume
            mountPath: /app/scripts/mem_stress_controlled.py
            subPath: mem_stress_controlled.py
      restartPolicy: Never
      volumes: 
        - name: results-volume
          hostPath: 
            path: /home/sdnuser/k8s-numa-benchmark/results
            type: DirectoryOrCreate
        - name: script-python-volume
          configMap:
            name: script-benchmark-controlled