apiVersion: v1
kind: Pod
metadata:
  name: benchmark-baseline-clean
  labels:
    app: benchmark-baseline
spec:
  nodeName: sdn2
  containers:
  - name: benchmark
    image: memory-benchmark:v_baseline_clean
    command: ["/bin/bash", "-c"]
    args:
      - |
        export OUTPUT_DIR=/app/results/baseline_clean
        export TARGET_NODE=0
        export POD_ID=$(hostname)
        numactl --cpunodebind=0 --membind=0 bash run_all.sh
    securityContext:
      privileged: true
    resources:
      requests:
        cpu: "1"
        memory: "3Gi"
      limits:
        cpu: "1"
        memory: "3Gi"
    volumeMounts:
    - name: results-volume
      mountPath: /app/results
  restartPolicy: Never
  volumes:
  - name: results-volume
    hostPath:
      path: /home/sdnuser/k8s-numa-benchmark/results
      type: DirectoryOrCreate
