---
apiVersion: batch/v1
kind: Job
metadata:
  name: bench-excr-n12-rand
spec:
  parallelism: 12
  completions: 12
  template:
    metadata:
      labels:
        app: bench-excr-n12-rand
    spec:
      nodeName: sdn2
      containers:
      - name: benchmark
        image: memory-benchmark:v_numa4
        command: ["/bin/bash", "-c"]
        args:
          - |
            export POD_ID=$(hostname)
            export OUTPUT_DIR=/app/results/bench-excr-n12-rand_${POD_ID}
            export BINDING_MODE="core"
            export PHYS_CPU_LIST="0,2,4,6,8,10,12,14,16,18,20,22"
            export MEM_NODE="1"
            export PATTERN="random"
            export EXPERIMENT_MODE="work"
            bash run_all.sh
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: results-volume
          mountPath: /app/results
        - name: script-python-volume
          mountPath: /app/scripts/script_controlled.py
          subPath: script_controlled.py
        - name: script-python-volume
          mountPath: /app/scripts/mem_stress_controlled.py
          subPath: mem_stress_controlled.py
        - name: script-python-volume
          mountPath: /app/run_all.sh
          subPath: run_all.sh
      restartPolicy: Never
      volumes:
      - name: results-volume
        hostPath:
          path: /home/sdnuser/k8s-numa-benchmark/results
          type: DirectoryOrCreate
      - name: script-python-volume
        configMap:
          name: script-benchmark-controlled
