apiVersion: batch/v1
kind: Job
metadata:
  name: overload-n24-rand
spec:
  parallelism: 24
  completions: 24
  template:
    metadata:
      labels:
        app: overload-n24-rand
    spec:
      nodeName: sdn2
      containers:
      - name: benchmark
        image: memory-benchmark:v_numa4
        command: ["/bin/bash", "-c"]
        args:
          - |
            export POD_ID=$(hostname)
            export OUTPUT_DIR=/app/results/diagnostics/overload-n24-rand/overload-n24-rand-${POD_ID}
            export EXPERIMENT_MODE="work"
            export PATTERN="random"

            mkdir -p "$OUTPUT_DIR"
            echo "--- OVERLOAD N24 RAND : 24 pods = tous les HyperThreads de sdn2 ---"
            cd /app
            python3 scripts/script_controlled.py --output-dir "$OUTPUT_DIR" --pattern "$PATTERN"

        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "1"
            memory: "1200Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: results-volume
          mountPath: /app/results
        - name: script-python-volume
          mountPath: /app/scripts/script_controlled.py
          subPath: script_controlled.py
        - name: script-python-volume
          mountPath: /app/scripts/mem_stress_controlled.py
          subPath: mem_stress_controlled.py
      restartPolicy: Never
      volumes:
      - name: results-volume
        hostPath:
          path: /home/sdnuser/k8s-numa-benchmark/results
          type: DirectoryOrCreate
      - name: script-python-volume
        configMap:
          name: script-benchmark-controlled
